### ISSUE TITLE
bug: sample in the documentation/tutorial does not work as expected

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [medyagh/setup-minikube#29] opened 2022-02-10 04:49 UTC
See https://github.com/kubernetes/minikube/issues/13595 for details

**Comment by medyagh** [comment] 2023-01-13 19:02
I think the problem is the service is not ready at the time, and need to wait for it first... one thing miinikube could do is do the wait for the user, we accept contributions to fix that

**Comment by spowelljr** [comment] 2024-06-21 22:30
This should be resolved with https://github.com/medyagh/setup-minikube/pull/478

**Closed** 2024-06-24 15:56 UTC
